### ISSUE TITLE
Get a haircut

### ISSUE THREAD

**Issue by charberg** [charberg/OEC#1]
I'll leave it to @danielsauve to review this one. @DavidBriglio

**Comment by DanielSauve** [comment]
Based on my current schedule this should be able to enter my "in progress" column on Saturday and shouldn't take more than a day to complete

**Comment by charberg** [comment]
@danielsauve  I'd really appreciate you working closely with @chrisB25 on this one.  I want you to make sure he's going down the right path for this one, and gets it done within the sprint if possible.

**Comment by DavidBriglio** [comment]
@danielsauve @chrisB25 We should focus on this during the retrospective, so please make this your top priority.

**Comment by charberg** [comment]
I've brought in a resident expert on chopping off much hair, @monicaruttle , to assist. Please advise.

**Comment by monicaruttle** [comment]
Will be taking myself off other tasks to focus on this issue.

**Comment by charberg** [comment]
@DavidBriglio Are you good to QA this?

**Comment by chrisB25** [comment]
![img_20160607_160336347](https://cloud.githubusercontent.com/assets/4054781/15872846/886bb01e-2cc9-11e6-9a93-864b656f2816.jpg)

Here is a sample of the issue.

Unfortunately, due to unforeseen circumstances, we will have to delay the resolution of the issue until September 12, 2016. Sorry for any and all inconveniences.

**Comment by monicaruttle** [comment]
Unfortunately, I have not seen a case get this far. Abort.

**Comment by charberg** [comment]
@monicaruttle No we need you, you're our private contractor. You're still under contract.

**Comment by charberg** [comment]
@chrisB25  Can we get an update on the progress on this issue?

**Comment by DavidBriglio** [comment]
Please see #2. I decided we should split task into two issues.

**Comment by chrisB25** [comment]
![img_20160707_111651351](https://cloud.githubusercontent.com/assets/4054781/16658467/80d492e4-4434-11e6-93b8-a7f3d074d7e9.jpg)
Update #2
